In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('../Capstone/eda_data.csv')

In [3]:
data.dtypes

Age                 int64
Sex                object
ChestPainType       int64
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina      int64
Oldpeak           float64
ST_Slope            int64
HeartDisease        int64
dtype: object

In [4]:
dfo = data.select_dtypes(include=['object'])
data = pd.concat([data.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)

In [5]:
data

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_F,Sex_M,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,1,140,289,0,172,0,0.0,0,0,0,1,0,1,0
1,49,2,160,180,0,156,0,1.0,1,1,1,0,0,1,0
2,37,1,130,283,0,98,0,0.0,0,0,0,1,0,0,1
3,48,3,138,214,0,108,1,1.5,1,1,1,0,0,1,0
4,54,2,150,195,0,122,0,0.0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,110,264,0,132,0,1.2,1,1,0,1,0,1,0
914,68,3,144,193,1,141,0,3.4,1,1,0,1,0,1,0
915,57,3,130,131,0,115,1,1.2,1,1,0,1,0,1,0
916,57,1,130,236,0,174,0,0.0,1,1,1,0,1,0,0
917,38,2,138,175,0,173,0,0.0,0,0,0,1,0,1,0

In [6]:
names = data.columns

In [7]:
scaler = StandardScaler()

In [8]:
scaled_df = scaler.fit_transform(data)

In [9]:
scaled_df = pd.DataFrame(scaled_df, columns=names)

In [10]:
scaled_df

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_F,Sex_M,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,-1.433140,-1.345086,0.410909,0.825070,-0.551341,1.382928,-0.823556,-0.832432,-1.052114,-1.113115,-0.515952,0.515952,-0.507478,0.814275,-0.490449
1,-0.478484,-0.270422,1.491752,-0.171961,-0.551341,0.754157,-0.823556,0.105664,0.596078,0.898380,1.938163,-1.938163,-0.507478,0.814275,-0.490449
2,-1.751359,-1.345086,-0.129513,0.770188,-0.551341,-1.525138,-0.823556,-0.832432,-1.052114,-1.113115,-0.515952,0.515952,-0.507478,-1.228087,2.038947
3,-0.584556,0.804242,0.302825,0.139040,-0.551341,-1.132156,1.214246,0.574711,0.596078,0.898380,1.938163,-1.938163,-0.507478,0.814275,-0.490449
4,0.051881,-0.270422,0.951331,-0.034755,-0.551341,-0.581981,-0.823556,-0.832432,-1.052114,-1.113115,-0.515952,0.515952,-0.507478,0.814275,-0.490449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,-2.419749,-1.210356,0.596393,-0.551341,-0.188999,-0.823556,0.293283,0.596078,0.898380,-0.515952,0.515952,-0.507478,0.814275,-0.490449
914,1.536902,0.804242,0.627078,-0.053049,1.813758,0.164684,-0.823556,2.357094,0.596078,0.898380,-0.515952,0.515952,-0.507478,0.814275,-0.490449
915,0.370100,0.804242,-0.129513,-0.620168,-0.551341,-0.857069,1.214246,0.293283,0.596078,0.898380,-0.515952,0.515952,-0.507478,0.814275,-0.490449
916,0.370100,-1.345086,-0.129513,0.340275,-0.551341,1.461525,-0.823556,-0.832432,0.596078,0.898380,1.938163,-1.938163,1.970528,-1.228087,-0.490449
917,-1.645286,-0.270422,0.302825,-0.217696,-0.551341,1.422226,-0.823556,-0.832432,-1.052114,-1.113115,-0.515952,0.515952,-0.507478,0.814275,-0.490449

In [11]:
X, y = scaled_df.dropna().drop(['HeartDisease'], axis=1), scaled_df.dropna()['HeartDisease']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=42)

In [13]:
x_train.shape

(688, 14)

In [14]:
x_test.shape

(230, 14)

In [15]:
x_train.head()

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,Sex_F,Sex_M,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
155,0.264027,0.804242,1.221541,1.309865,1.813758,0.518368,1.214246,1.981855,0.596078,-0.515952,0.515952,-0.507478,0.814275,-0.490449
362,0.264027,-0.270422,1.221541,-1.818435,-0.551341,-1.485840,-0.823556,-0.832432,0.596078,-0.515952,0.515952,-0.507478,-1.228087,2.038947
869,0.582246,-0.270422,0.951331,0.120745,1.813758,0.793455,-0.823556,0.668521,-1.052114,-0.515952,0.515952,-0.507478,0.814275,-0.490449
101,-0.266338,0.804242,-0.129513,-0.181108,-0.551341,-1.446542,-0.823556,-0.832432,-1.052114,-0.515952,0.515952,-0.507478,0.814275,-0.490449
199,0.370100,-2.419749,-0.129513,0.998865,-0.551341,-1.525138,-0.823556,0.105664,0.596078,1.938163,-1.938163,-0.507478,0.814275,-0.490449